### ISSUE TITLE
Compose with image to multipes account failure

### ISSUE THREAD

**Issue by hungdm9999** [socioboard/Socioboard-Core-3.0#17]
Composing to multiple accounts show success popup but actually failure behind. The reason was exception when accessing one image file multiples time, as detail below:
Message=The process cannot access the file 'C:\work\Socioboard-Core-3.0-master\src\Api.Socioboard\wwwroot\upload\MZKEFRWLQ8.jpg' because it is being used by another process.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
       at System.IO.FileStream..ctor(String path, FileMode mode)
       at Api.Socioboard.Controllers.MediaController.Get(String id) in C:\work\Socioboard-Core-3.0-master\src\Api.Socioboard\Controllers\MediaController.cs:line 75
       at lambda_method(Closure , Object , Object[] )
       at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
       at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
  InnerException: 

<code>SOLUTION</code>
Please modify the file <code>Modify Api.Socioboard.MediaController.cs</code> at line 75 with access-mode = READ, as below
`  [HttpGet("Get")]
        public IActionResult Get(string id)
        {
            MemoryStream ms = null;
            //Limit access only to images folder at root level  
            string filePath = _appEnv.WebRootPath + string.Concat("/upload/", id);
            string extension = Path.GetExtension(id);
            if (System.IO.File.Exists(filePath))
            {
                if (!string.IsNullOrWhiteSpace(extension))
                {
                    extension = extension.Substring(extension.IndexOf(".") + 1);
                }

                //If requested file is an image than load file to memory  
                if (GetImageFormat(extension) != null)
                {
					//return Ok(new FileStream(filePath, FileMode.Open));
                    return Ok(new FileStream(filePath, FileMode.Open, FileAccess.Read));

                    //ms = CopyFileToMemory(filePath);
                }
                if (extension.ToLower().Equals("mp4") || extension.ToLower().Equals("mov") || extension.ToLower().Equals("mpeg") || extension.ToLower().Equals("wmv") || extension.ToLower().Equals("avi") || extension.ToLower().Equals("flv") || extension.ToLower().Equals("3gp"))
                {
					//return Ok(new FileStream(filePath, FileMode.Open));
                    return Ok(new FileStream(filePath, FileMode.Open, FileAccess.Read));
                }
            }

            return BadRequest();
 }`

**Comment by socioboard** [comment]
Hi hungdm9999 ,
We are working on the same. when it finish will let you know.

Thanks
SB Technical Team
