### ISSUE TITLE
Exception thrown: 'System.NotSupportedException' in NHibernate.dll

### ISSUE THREAD

**Issue by gnh1201** [socioboard/Socioboard-Core-3.0#63]
Exception thrown: 'System.NotSupportedException' in NHibernate.dll

```
Exception thrown: 'System.NotSupportedException' in NHibernate.dll
Api.Socioboard.Controllers.UserController: Critical: PartialEvalException (InvalidOperationException ("Sequence contains no elements"), PartialEvalException (InvalidOperationException ("Sequence contains no elements"), {value(System.Collections.Generic.List`1[Domain.Socioboard.Models.Facebookaccounts]) => First()}).UserId)
Api.Socioboard.Controllers.UserController: Error:    at NHibernate.Linq.Visitors.HqlGeneratorExpressionTreeVisitor.VisitExpression(Expression expression)
   at NHibernate.Linq.Visitors.HqlGeneratorExpressionTreeVisitor.VisitBinaryExpression(BinaryExpression expression)
   at NHibernate.Linq.Visitors.HqlGeneratorExpressionTreeVisitor.VisitExpression(Expression expression)
   at NHibernate.Linq.Visitors.QueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at NHibernate.Linq.Visitors.QueryModelVisitor.GenerateHqlQuery(QueryModel queryModel, VisitorParameters parameters, Boolean root)
   at NHibernate.Linq.NhLinqExpression.Translate(ISessionFactoryImplementor sessionFactory, Boolean filter)
   at NHibernate.Hql.Ast.ANTLR.ASTQueryTranslatorFactory.CreateQueryTranslators(IQueryExpression queryExpression, String collectionRole, Boolean shallow, IDictionary`2 filters, ISessionFactoryImplementor factory)
   at NHibernate.Engine.Query.QueryPlanCache.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow, IDictionary`2 enabledFilters)
   at NHibernate.Impl.AbstractSessionImpl.GetHQLQueryPlan(IQueryExpression queryExpression, Boolean shallow)
   at NHibernate.Impl.AbstractSessionImpl.CreateQuery(IQueryExpression queryExpression)
   at NHibernate.Linq.DefaultQueryProvider.PrepareQuery(Expression expression, IQuery& query, NhLinqExpression& nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Api.Socioboard.Model.DatabaseRepository.Find[T](Expression`1 query)
Exception thrown: 'System.NullReferenceException' in Api.Socioboard.exe
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'System.Collections.Generic.KeyNotFoundException' in mscorlib.dll
Exception thrown: 'NHibernate.MappingException' in NHibernate.dll
Api.Socioboard.Controllers.UserController: Critical: No persister for: Domain.Socioboard.Models.User
Api.Socioboard.Controllers.UserController: Error:    at NHibernate.Impl.SessionFactoryImpl.GetEntityPersister(String entityName)
   at NHibernate.Impl.SessionImpl.GetEntityPersister(String entityName, Object obj)
   at NHibernate.Event.Default.AbstractSaveEventListener.SaveWithGeneratedId(Object entity, String entityName, Object anything, IEventSource source, Boolean requiresImmediateIdAccess)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.SaveWithGeneratedOrRequestedId(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.EntityIsTransient(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveEventListener.PerformSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Event.Default.DefaultSaveOrUpdateEventListener.OnSaveOrUpdate(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.FireSave(SaveOrUpdateEvent event)
   at NHibernate.Impl.SessionImpl.Save(Object obj)
   at Api.Socioboard.Model.DatabaseRepository.Add[T](T item)
Exception thrown: 'System.InvalidOperationException' in NHibernate.dll
Api.Socioboard.Controllers.UserController: Critical: Sequence contains no elements
Api.Socioboard.Controllers.UserController: Error:    at NHibernate.Linq.DefaultQueryProvider.ExecuteQuery(NhLinqExpression nhLinqExpression, IQuery query, NhLinqExpression nhQuery)
   at NHibernate.Linq.DefaultQueryProvider.Execute(Expression expression)
   at NHibernate.Linq.DefaultQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at Api.Socioboard.Model.DatabaseRepository.Single[T](Expression`1 expression)
Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor: Information: Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Executed action Api.Socioboard.Controllers.UserController.FacebookLogin (Api.Socioboard) in 6014.5145ms
Application Insights Telemetry (unconfigured): {"name":"Microsoft.ApplicationInsights.Dev.Request","time":"2018-02-07T07:21:58.2580357Z","tags":{"ai.internal.sdkVersion":"aspnet5f:1.0.0","ai.operation.id":"lwUMP0HXr94=","ai.location.ip":"127.0.0.1","ai.operation.name":"POST User/FacebookLogin","ai.device.roleInstance":"TULIP-VM"},"data":{"baseType":"RequestData","baseData":{"ver":2,"id":"lwUMP0HXr94=","name":"POST User/FacebookLogin","startTime":"2018-02-07T07:21:58.2580357+00:00","duration":"00:00:06.0192268","success":true,"responseCode":"204","url":"http://example.org:6361/api/User/FacebookLogin","httpMethod":"POST","properties":{"DeveloperMode":"true"}}}}
Microsoft.AspNetCore.Hosting.Internal.WebHost: Information: Request finished in 6031.178ms 204 
The thread 0x88 has exited with code 0 (0x0).
```

**Comment by socioboard** [comment]
Hi gnh1201,
give proper connection string .

Thanks 
SB Team

**Comment by socioboard** [comment]
Hi gnh1201,
I hope you have found the solution for it .
For now am closing this issue if any prob in future let us know

Thanks
SB Team
